version: '3'
services:
  sql-server:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_USER=user
    ports:
      - "${MY_SQL_PORT}:3306"
    networks:
      - app-network
  controller:
    build: 
      context: ./controller
      dockerfile: Dockerfile
    ports:
      - "${CONTROLLER_PORT}:3000"
    environment:
      - MY_SQL_HOST=${MY_SQL_HOST}
    depends_on:
      - sql-server
    networks:
      - app-network
networks:
  app-network:
    driver: bridge