version: '3'
services:
  central:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_USER=user
    ports:
      - "3000:3306"
  node2:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_USER=user
    ports:
      - "3001:3306"
  node3:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_USER=user
    ports:
      - "3002:3306"