services:
  sql-server:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_USER=user
    ports:
      - "${MY_SQL_PORT}:3306"
    networks:
      - app-network
    volumes:
      - ./sql-data/${MY_SQL_HOST}:/var/lib/mysql

  controller:
    build: 
      context: ./controller
      dockerfile: Dockerfile
    ports:
      - "${CONTROLLER_PORT}:${CONTROLLER_PORT}"
    environment:
      - CONTROLLER_PORT=${CONTROLLER_PORT}
      - MY_SQL_HOST=${MY_SQL_HOST}
      - MY_SQL_PORT=${MY_SQL_PORT}
      - PEER_CONTROLLER_HOSTS=${PEER_CONTROLLER_HOSTS}
    depends_on:
      - sql-server
    networks:
      - app-network
networks:
  app-network:
    driver: bridge