services:
  sql-server:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_USER=user
    ports:
      - "${MY_SQL_PORT}:3306"
    networks:
      - app-network
    # if you want to init a schema, uncomment the line below:
    volumes:
      - ./sql/00_create.sql:/docker-entrypoint-initdb.d/00_create.sql
      - ./sql/procedures.sql:/docker-entrypoint-initdb.d/procedures.sql
      - ./sql/${NAME}.sql:/docker-entrypoint-initdb.d/${NAME}.sql
      - ./sql-data/${NAME}:/var/lib/mysql

networks:
  app-network:
    driver: bridge