version: '3'
services:
  sql-server:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_USER=user
    ports:
      - "${MY_SQL_PORT}:3306"
    networks:
      - app-network
    # if you want to init a schema, uncomment the line below:
    # volumes:
    #   - ./sql/${MY_SQL_HOST}:/docker-entrypoint-initdb.d
    volumes:
      - ./sql-data/${MY_SQL_HOST}:/var/lib/mysql

networks:
  app-network:
    driver: bridge